---
title: 'Figure 6: Defining resilience and susceptibility'
format:
    html:
        code-fold: false
        self-contained: true
        toc: true
editor:
    render-on-save: false
---

### Libraries and Config

```{r}
#| label: libraries
#| message: false
#| code-fold: true

library(here)
library(glue)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(cowplot)
```

```{r}
#| label: config + paths + data
#| code-fold: true

source(here('styles.R'))
data_path <- here('data')
primary_diff <- readRDS(glue('{data_path}/SIT_diff_primary.rds'))
secondary_diff <- readRDS(glue('{data_path}/SIT_diff_secondary.rds'))

# Bind primary and secondary DFs 
primary_diff %<>%
    mutate(model = 'CSW/DS',
           lab = 'bagot') %>%
    select(names(secondary_diff)) 
SIT_diff <- bind_rows(primary_diff, secondary_diff) %>%
                      mutate(model = factor(model, levels = c('CSW/DS', 'CSNDS', 'Urine')),
                             full_cond = paste(Sex, Condition))
```

------------------------------------------------------------------------

### Relationship between SI Ratio and $\Delta$ Velocity (Fig. 6a)

Si data are binned before plotting. The majority of SI ratio values are within 1 - 2, with only sparse coverage below 1. We are specifically interested in the relationship between low SI ratio values and $\Delta$Velocity, and without binning the data, the relationship to lower values will be difficult to understand due to their sparsity.

```{r}
#| label: SI ratio bins + Fig. 6a prep
#| code-fold: true

# Bin data
SIT_diff %>% 
  mutate(SI_bin = cut(IZ_time, breaks = seq(0, max(IZ_time) + 0.1, .25))) %>%
  mutate(SI_bin = gsub('\\(', '', gsub('\\]', '', gsub('\\,', ' - ', SI_bin)))) -> SIT_diff

# Make labels look pretty
SIT_diff$SI_bin[grepl('0 ', SIT_diff$SI_bin)] <- gsub('0 ','0.00 ', 
                                                      SIT_diff$SI_bin[grepl('0 ', SIT_diff$SI_bin)])
SIT_diff$SI_bin[grepl('0.5 ', SIT_diff$SI_bin)] <- gsub('0.5 ','0.50 ', 
                                                      SIT_diff$SI_bin[grepl('0.5 ', SIT_diff$SI_bin)])
SIT_diff$SI_bin[grepl(' 0.5', SIT_diff$SI_bin)] <- gsub(' 0.5$',' 0.50', 
                                                      SIT_diff$SI_bin[grepl(' 0.5', SIT_diff$SI_bin)])
SIT_diff$SI_bin[grepl('1 ', SIT_diff$SI_bin)] <- gsub('1 ','1.00 ', 
                                                      SIT_diff$SI_bin[grepl('1 ', SIT_diff$SI_bin)])
SIT_diff$SI_bin[grepl(' 1', SIT_diff$SI_bin)] <- gsub(' 1$',' 1.00', 
                                                      SIT_diff$SI_bin[grepl(' 1', SIT_diff$SI_bin)])
SIT_diff$SI_bin[grepl('1.5 ', SIT_diff$SI_bin)] <- gsub('1.5 ','1.50 ', 
                                                      SIT_diff$SI_bin[grepl('1.5 ', SIT_diff$SI_bin)])
SIT_diff$SI_bin[grepl(' 1.5', SIT_diff$SI_bin)] <- gsub(' 1.5$',' 1.50', 
                                                      SIT_diff$SI_bin[grepl(' 1.5', SIT_diff$SI_bin)])
SIT_diff$SI_bin[grepl(' 2', SIT_diff$SI_bin)] <- gsub(' 2$',' 2.00', 
                                                      SIT_diff$SI_bin[grepl(' 2', SIT_diff$SI_bin)])
SIT_diff$SI_bin[SIT_diff$IZ_time > 2] <- '2.00 +'
SIT_diff$SI_bin_window <- ifelse(SIT_diff$IZ_time > 2, 'B', 'A')
SIT_diff$model <- factor(SIT_diff$model, levels = c('CSW/DS', 'CSNDS', 'Urine'))
```

```{r}
#| label: Fig 6a plot
#| code-fold: true
#| fig-width: 10
#| fig-asp: 0.65
#| fig-align: center

ggplot(SIT_diff, aes(SI_bin, Velocity)) + 
  geom_vline(xintercept = 4.5) + 
  geom_jitter(aes(color = full_cond), 
              width = 0.1, alpha = 0.5, size = 2, height = 0) +
  stat_summary(aes(shape = model), fun = 'mean', geom = 'point', size = 2) + 
  stat_summary(aes(group = model, linetype = model), 
               fun.data = 'mean_se', geom = 'line', 
               linewidth = 1) + 
  scale_y_continuous(name = expression(Delta*' Velocity'), 
                     limits = c(-4,10), breaks = c(-4,-2,0,2,4,6,8,10)) + 
  scale_x_discrete(name = 'SI Ratio (Binned)') + 
  scale_color_manual(values = col_full) + 
  scale_fill_manual(values = col_full) +
  facet_grid(. ~ Sex, scales = 'free', space = 'free') +
  plot_theme + 
  theme(legend.position = 'bottom',
         axis.text.x = element_text(angle = 45, hjust = 1),#, vjust = 0.5),
         strip.text = element_blank())
```

### Resilience/susceptibility cut-offs (Fig. 6b)

We are proposing a distribution based cut-off for $\Delta$Velocity

```{r}
#| label: Fig 6b plot
#| code-fold: true
#| fig-width: 7.5
#| fig-asp: 1
#| fig-align: center
#| warning: false

Cor_plot <- ggplot(SIT_diff[SIT_diff$Sex == 'Female',], aes(IZ_time, Velocity)) + 
                      geom_segment(aes(x = 1, xend = 3.2, y = 1.5, yend = 1.5)) +
                      geom_segment(aes(x = 1, xend = 1, y = 1.5, yend = 9.3)) +
                      geom_point(data = SIT_diff[SIT_diff$Sex == 'Female' &
                                              SIT_diff$IZ_time > 1 & SIT_diff$Velocity > 1.5,], 
                                              aes(color = Condition, shape = model), size = 2, alpha = 0.3) + 
                      geom_point(data = SIT_diff[SIT_diff$Sex == 'Female' &
                                              (SIT_diff$IZ_time < 1 | SIT_diff$Velocity < 1.5),], 
                                              aes(color = Condition, shape = model), size = 3, alpha = 0.7) + 
                      scale_color_manual(values = col_full) +
                      scale_x_continuous(limits = c(0,3.2)) + 
                      xlab('SI Ratio') + ylab(expression(Delta*' Velocity')) +
                      plot_theme + 
                      theme(legend.position = 'none',
                            plot.margin = unit(c(0,0,0,0), 'cm'))

SI_hist <- ggplot(SIT_diff[SIT_diff$Sex == 'Female',], 
                  aes(IZ_time, color = Condition, fill = Condition)) + 
              geom_density(alpha = 0.4) + 
              geom_vline(xintercept = 1) + 
              scale_color_manual(values = col_full) + 
              scale_fill_manual(values = col_full) + 
              scale_x_continuous(limits = c(0,3.2)) + 
              plot_theme +
              clean_theme() + 
              theme(legend.position = 'none',
                    plot.margin = unit(c(0,0,0,0), 'cm')) 

DelVel_hist <- ggplot(SIT_diff[SIT_diff$Sex == 'Female',], 
                      aes(Velocity, color = Condition, fill = Condition)) + 
                  geom_density(alpha = 0.4) + 
                  geom_vline(xintercept = 1.5) + 
                  scale_color_manual(values = col_full) + 
                  scale_fill_manual(values = col_full) + 
                  plot_theme +
                  coord_flip() +
                  clean_theme() + 
                  theme(legend.position = 'none',
                        plot.margin = unit(c(0,0,0,0), 'cm'))

plot_grid(SI_hist, NULL, Cor_plot, DelVel_hist, align = 'hv', 
          rel_widths = c(3,1), rel_heights = c(1,3))
```

------------------------------------------------------------------------

### General stress-induced phenotype in OFT (Fig. S4)

In males, the OFT is used

```{r}

```